version: "3.5"
services:
    mosquitto:
        image: eclipse-mosquitto:1.6
        container_name: mosquitto
        ports:
          - 1883:1883
        volumes:
        - type: bind
          source: ./mosquitto.conf
          target: /mosquitto/config/mosquitto.conf
          read_only: true

    ttsub:
        image: tt:latest
        container_name: test-mosquitto
        command: /tt sub -s broker:1883
        depends_on:
          - mosquitto

    ttserve:
        image: tt:latest
        container_name: ttserve
        ports:
          - 1882:1882
        command: /tt srv -b "tcp://:1882"

    ttsubserv:
        image: tt:latest
        container_name: test-ttserve
        command: /tt sub -s ttserve:1882
        depends_on:
          - ttserve
          
