version: "3.5"
services:
    mosquitto:
        image: eclipse-mosquitto:1.6
        container_name: mosquitto
        volumes:
        - type: bind
          source: ./mosquitto.conf
          target: /mosquitto/config/mosquitto.conf
          read_only: true

        - type: bind
          source: ./passwd
          target: /mosquitto/config/passwd
          read_only: true

    ttsub:
        image: tt:latest
        container_name: test-mosquitto
        command: /tt sub -s mosquitto:2883
        depends_on:
          - mosquitto

    ttsrv:
        image: tt:latest
        container_name: ttsrv
        ports:
          - 1882:1882
        command: /tt srv -b "tcp://:1882"

    ttsubsrv:
        image: tt:latest
        container_name: test-ttsrv
        command: /tt sub -s ttsrv:1882
        depends_on:
          - ttsrv
          
