name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up tools
      run: go run ci.go setup

    - name: Install tt
      run: go run ci.go install

    - name: Test
      run: go run ci.go test | gocolor
